name: Cargo-Pushish

on:
  release:
    types: [created]
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    uses: ./.github/workflows/rust-test.yml
  publish:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - uses: actions/checkout@v3
        - name: Check
          run: cargo check --verbose
