name: Cargo-Pushish

on:
  release:
    types: [created]
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    uses: ./.github/workflows/rust-test.yml
  publish:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - uses: actions/checkout@v3
        - name: Login
          run: cargo login ${{ secrets.CARGO_TOKEN }} --verbose
        - name: Publish
          run: |
            cargo package --list
            cargo publish
